dataset:
  LVOS_2:
    train: https://drive.google.com/uc?id=1-ehpl5s0Fd14WwtT-GmWtIWa_BxZl9D6
    val: https://drive.google.com/uc?id=17Hwc__6i2rpF5e2s5OPqoywNxG5bzlcO
    test: https://drive.google.com/uc?id=1Vp_y8dSUO4ktYmeBFkIQnmAxK6bl3Eyf
  # If you want to add LVOS_1


attributes:  # Only available for the LVOS 2 version
  train: https://drive.google.com/uc?id=1oYjE20adHsej-Zeiat2d4bP8H7EoZFSy
  val: https://drive.google.com/uc?id=1IRzRLUOvDBazalE895xa-bT8C8Qi5O9R
  test: https://drive.google.com/uc?id=1kqVJSCJdrT32j4hsIPb9URClRfYZxI66




destination: ../../../WORK_Station/VOS/UVOS/datasets/